// объявление необходимых констант

import Loader from './Loader';
const messageForm = document.getElementById('message-form'),
  typeMessageInput = document.getElementById('type-message'),
  chatContainer = document.querySelector('.messanger__chat-container'),
  chat = document.getElementById('chat'),
  addFileInput = document.getElementById('add-file-input'),
  addFileBtn = document.getElementById('add-file-btn'),
  loader = new Loader(),
  mediaButtons = document.querySelector('.messanger__composer-btns'),
  mediaControllers = document.querySelector('.messanger__record-media'),
  recAudioBtn = document.getElementById('rec-audio-btn'),
  recVideoBtn = document.getElementById('rec-video-btn'),
  clearMediaBtn = document.getElementById('clear-media-btn'),
  sendMediaBtn = document.getElementById('send-media-btn'),
  mediaTimer = document.getElementById('media-timer'),
  searchForm = document.getElementById('search-form'),
  searchInput = document.getElementById('search-message'),
  noResultAlarm = document.querySelector('.messanger__no-search'),
  showFavoriteBtn = document.getElementById('show-favorite-btn'),
  sendGeoBtn = document.getElementById('send-geo-btn');

export {
  messageForm,
  typeMessageInput,
  chat,
  chatContainer,
  addFileInput,
  addFileBtn,
  loader,
  mediaButtons,
  mediaControllers,
  recAudioBtn,
  recVideoBtn,
  clearMediaBtn,
  sendMediaBtn,
  mediaTimer,
  searchForm,
  searchInput,
  noResultAlarm,
  showFavoriteBtn,
  sendGeoBtn,
};
